<?php

namespace Container0ABdwU7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TrYjlnNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.trYjlnN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.trYjlnN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'encoder' => ['privates', '.errored.zurRrsp', NULL, 'Cannot determine controller argument for "App\\Controller\\UsersController::editPassword()": the $encoder argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserPasswordEncoderInterface". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
            'encoder' => '?',
        ]);
    }
}
