<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBUtsGRk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBUtsGRk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBUtsGRk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBUtsGRk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBUtsGRk\App_KernelDevDebugContainer([
    'container.build_hash' => 'BUtsGRk',
    'container.build_id' => '7d4c68ff',
    'container.build_time' => 1663942779,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBUtsGRk');
